### ISSUE TITLE
添加房型的数据接口中希望增加如下字段

### ISSUE THREAD

**Issue by lovelts** [B-A-R-team/ehotel-server#2]
![12345679](https://user-images.githubusercontent.com/49828603/94883900-6cb3d200-049e-11eb-9cbe-2f6de2f69981.png)

一般相同的房型的楼层和面积 都一样 ，因此希望在房型这里增加这两个字段。并且希望在后台统计好每个房型 房间的总数和 剩余，在获取所有房型的接口中返回相应数据

**Comment by Tuzilow** [comment]
完成
